{"name": "test_TC_SUR_05_special_characters_input", "status": "failed", "statusDetails": {"message": "AssertionError: Form incorrectly accepted \nassert 'Survey Resp...successfully' not in 'Survey Resp...ur feedback.'\n  \n  'Survey Response: S...mitted successfully' is contained here:\n    Survey Response: Survey submitted successfully, Thank you for your feedback.", "trace": "self = <test_cases.test_survey_form.TestContactForm object at 0x10375c080>\n\n>   ???\nE   AssertionError: Form incorrectly accepted \nE   assert 'Survey Resp...successfully' not in 'Survey Resp...ur feedback.'\nE     \nE     'Survey Response: S...mitted successfully' is contained here:\nE       Survey Response: Survey submitted successfully, Thank you for your feedback.\n\n/Users/tinopro14/Documents/TESTING SCRIPTS/tino-dev-testing/test_cases/test_survey_form.py:84: AssertionError"}, "start": 1749154882591, "stop": 1749154883788, "uuid": "fa628c5f-b493-417f-8d7e-e765cdf5d597", "historyId": "a3c16e8209231bd2dcfe528d4ac724b1", "testCaseId": "a3c16e8209231bd2dcfe528d4ac724b1", "fullName": "test_cases.test_survey_form.TestContactForm#test_TC_SUR_05_special_characters_input", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_driver')"}, {"name": "parentSuite", "value": "test_cases"}, {"name": "suite", "value": "test_survey_form"}, {"name": "subSuite", "value": "TestContactForm"}, {"name": "host", "value": "tinos-MBP14"}, {"name": "thread", "value": "24217-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_cases.test_survey_form"}]}